### ISSUE TITLE
results of Sensitivity Analysis

### ISSUE THREAD

**Issue by butybone** [liuyixin-louis/Stable-Unlearnable-Example#1]
您好，请问论文中Sensitivity Analysis章节中关于Early Stopping and Partial Poisoning部分的实验结果（Table 5）， Clean Ratio 参数是否等价于代码中的 1-noise_rate?
使用您的代码复现noise_rate=20%时，发现训练到step=20000（test_acc =89.16%）及以后时效果远远不如Table 5中的效果好，不知道是否正常？

**Comment by liuyixin-louis** [comment]
Hi, clean rate是和 1-noise_rate等价。

另外表中的$S_es$是early stop的#patience step，而不是训练的step数。表中并无Clean Rate=80% / Noise Rate = 20% 的结果，请参考70%和50%的结果对比

<img width="675" alt="image" src="https://github.com/liuyixin-louis/Stable-Unlearnable-Example/assets/53036760/e7765cac-3698-424c-82e3-5c2d5df061e7">
